---
- name: add apt repo 1
  become: true
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add apt repo 2
  become: true
  apt_repository: 
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    update_cache: yes

- name: apt install kubelet kubectl
  become: true
  apt: 
    name: 
      - kubeadm
      - kubelet 
      - kubectl
    state: latest
  tags: kube

- name: check swap state
  shell: swapon -v
  register: swap_state
  check_mode: false
  changed_when: false

- name: swap off
  become: true
  shell: swapoff -a
  when: swap_state.stdout != ''

- name: swap check (/etc/fstab)
  shell: grep -v "\s*#" /etc/fstab | awk '{print $2}' | grep swap -c
  register: swap_state_in_fstab
  check_mode: false
  changed_when: false
  ignore_errors: true

- name: disable swap (/etc/fstab)
  become: true
  replace:
    path: /etc/fstab
    regexp: ([^\s]+\s+swap\s+.*)
    replace: '# \1'
  when: swap_state_in_fstab.stdout != '0'

