---
- hosts: localhost
  connection: local
  tasks:
      - name: create group
        os_user_group:
            cloud: internal
            user: testuser1
            group: testers
            state: present
