---
- hosts: localhost
  connection: local
  tasks:
      - name: disable user
        os_user:
            cloud: internal
            name: testuser1
            state: present
            enabled: False
