---
- name: Install RemiRepositories
  yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
- name: Install php-fpm related
  yum:
      name: "{{ item }}"
      enablerepo: "remi-php{{ php_fpm_php_version|replace('.','') }}"
  with_items:
      - php-fpm
      - php-devel
      - php-enchant
      - php-mbstring
      - php-process
      - php-xml
      - php-gd
      - "{{ php_fpm_additional_packages }}"
  notify:
      - Reload PHP-FPM
- name: Reload PHP-FPM
  service:
      name: php-fpm
      state: started
      enabled: true
