---
- name: Playbook tutorial
  hosts: all
  become: true
  tasks:
      - name: libselinux-python install
        yum:
            name: libselinux-python
            state: present
      - name: EPELrepositories install
        yum:
            name: epel-release
            state: present
      - name: Nginx install
        yum:
            name: nginx
            state: present
      - name: Nginx start and enable.
        service:
            name: nginx
            state: started
            enabled: true
