---
- name: libselinux-python and EPELrepositories install
  yum:
      name: "{{ item }}"
      state: present
  with_items:
      - libselinux-python
      - epel-release
- name: Nginx install
  yum:
      name: nginx
      state: present
- name: Nginx start and enable.
  service:
      name: nginx
      state: started
      enabled: true
- name: nginx.conf(template)Open
  template:
      src: nginx.j2.conf
      dest: /etc/nginx/nginx.conf
      validate: nginx -t -c %s
  notify:
      - Nginx Reload
