---
- name: Install SELinux for Python
  yum:
      name: "{{ item }}"
  with_items:
      - libselinux-python
      - policycoreutils-python
- name: Disable SELinux
  selinux:
      policy: targeted
      state: permissive
  register: common_make_selinux_permissive
- block:
    - name: Reboot according to SELinux status
      shell: sleep 2 && shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
      changed_when: true
    - name: RebootWait
      local_action: wait_for
      args:
          host: "{{ ansible_host|default(inventory_hostname) }}"
          port: "{{ ansible_ssh_port|default(22) }}"
          state: started
          search_regex: OpenSSH
          delay: 60
          timeout: 600
      become: false
  when: common_make_selinux_permissive|changed and 'state change will take effect next reboot' in common_make_selinux_permissive.msg
- name: Enable firewall
  service:
      name: firewalld
      state: started
      enabled: true
