---
- hosts: localhost
  connection: local
  tasks:
      - name: Create subnet of prod-public
        os_network:
            cloud: production
            state: present
            name: prod-subnet-hb
            network_name: prod-heartbeat
            cidr: 192.168.1.0/24
            no_gateway_ip: true
