---
- hosts: localhost
  connection: local
  tasks:
      - name: Create flavor t2.nano
        os_nova_flavor:
            cloud: production
            name: t2.nano
            state: present
            vcpus: 1
            ram: 512
            disk: 0
