---
- hosts: localhost
  connection: local
  tasks:
      - name: reset user password
        os_user:
            cloud: internal
            name: testuser1
            state: present
            password: reset_the_password!
