---
- name: Install SELinux for Python
  yum:
      name: "{{ item }}"
  with_items:
      - libselinux-python
      - policycoreutils-python
- name: Disable SELinux
  selinux:
      policy: targeted
      state: permissive
  register: common_make_selinux_permissive
