---
- name: Setup Wordpress for CentOS
  hosts: all
  become: true
  vars:
      db_name: wordpress
      db_user: wordpress
      db_password: mysQ1InsecureP@ssw0rd
  roles:
      - name: common
        tags:
            - common
      - name: mariadb
        tags:
            - mariadb
        vars:
            mariadb_databases:
                - name: "{{ db_name }}"
            mariadb_users:
                - name: "{{ db_user }}"
                  password: "{{ db_password }}"
                  priv: "{{ db_name }}.*:ALL"
      - name: php-fpm
        tags:
            - php-fpm
        vars:
            php_fpm_additional_packages:
                - php-mysqlnd
      - name: nginx
        tags:
            - nginx
        vars:
            nginx_default_port: 8080
      - name: wordpress
        tags:
            - wordpress
        vars:
            wordpress_db_name: "{{ db_name }}"
            wordpress_db_user_name: "{{ db_user }}"
            wordpress_db_user_password: "{{ db_password }}"
            wordpress_nginx_user: "{{ nginx_user }}"
            wordpress_nginx_group: "{{ nginx_config_dir }}"
            wordpress_nginx_config_dir: "{{ php_fpm_config_dir }}"
