---
- hosts: master
  roles:
    - common
    - docker
    - kube
  tasks:
    - name: install kubeadm
      become: true
      apt: name=kubeadm state=latest
    - name: kubeadm init
      become: true
      shell: kubeadm init --apiserver-advertise-address={{ ansible_eth0.ipv4.address }} --pod-network-cidr=10.244.0.0/16

