---
- name: apt update and upgrade
  become: true
  apt:
    update_cache: yes
    upgrade: yes
  
- name: check swap state
  shell: swapon -v
  register: swap_state
  check_mode: false
  changed_when: false

- name: swap off
  become: true
  shell: swapoff -a
  when: swap_state.stdout != ''

- name: swap check (/etc/fstab)
  shell: grep -v "\s*#" /etc/fstab | awk '{print $2}' | grep swap -c
  register: swap_state_in_fstab
  check_mode: false
  changed_when: false
  ignore_errors: true

- name: disable swap (/etc/fstab)
  become: true
  replace:
    path: /etc/fstab
    regexp: ([^\s]+\s+swap\s+.*)
    replace: '# \1'
  when: swap_state_in_fstab.stdout != '0'


