---
- name: libselinux-python and EPELrepositories install
  yum:
      name: "{{ item }}"
      state: present
  with_items:
      - libselinux-python
      - epel-release
- name: Nginx install
  yum:
      name: nginx
      state: present
- name: Nginx start and enable.
  service:
      name: nginx
      state: started
      enabled: true
- name: nginx.conf(template)Open
  template:
      src: nginx.j2.conf
      dest: /etc/nginx/nginx.conf
      validate: nginx -t -c %s
  notify:
      - Reload Nginx
- name: Create Nginx Groups
  group:
      name: "{{ nginx_group }}"
      system: true
- name: Create Nginx User
  user:
      name: "{{ nginx_user }}"
      home: /var/lib/nginx
      shell: /sbin/nologin
      groups: "{{ nginx_group }}"
      append: true
      system: true
